module.exports = {
    GET_ALL_CATEGORIES: "GET_ALL_CATEGORIES",
    GET_ALL_POSTS: "GET_ALL_POSTS",
    GET_POSTS_FOR_CATEGORY: "GET_POSTS_FOR_CATEGORY",
    SORT_POSTS: "SORT_POSTS",
    CREATE_NEW_POST: "CREATE_NEW_POST",
    VOTE_POST: "VOTE_POST",
    EDIT_POST: "EDIT_POST",
    LOAD_POST: "LOAD_POST",
    LOAD_COMMENTS_FOR_POST: "LOAD_COMMENTS_FOR_POST",
    LOAD_POST_AND_COMMENTS: "LOAD_POST_AND_COMMENTS"
};